### ISSUE TITLE
can you provide db.sql ?

### ISSUE THREAD

**Issue by yjhjstz** [mynameisankit/real-estate-management-system#1]
can you provide sql for mysql or postgresql ?

**Comment by mynameisankit** [comment]
Sorry, I never committed the `db.sql` file. Maybe I will make and save one in future, but I am not sure it is worth it

**Comment by yjhjstz** [comment]
since https://real-estate-management-system.vercel.app/buyer can not open ,  so db.sql is need to rebuild project.
many thanks.
